<?php

define("LOG_LOGIN", 1);
define("LOG_LOGOUT", 2);

define("LOG_LISTAR_ENTRADA", 3);
define("LOG_ADD_ENTRADA", 4);
define("LOG_UPDATE_ENTRADA", 5);
define("LOG_DELETE_ENTRADA", 6);

define("LOG_LISTAR_MOSCA", 7);
define("LOG_ADD_MOSCA", 8);
define("LOG_UPDATE_MOSCA", 9);
define("LOG_DELETE_MOSCA", 10);

define("LOG_LISTAR_PARRILLA", 11);
define("LOG_ADD_EVENTO", 12);
define("LOG_DELETE_EVENTO", 13);
define("LOG_MOVE_EVENTO", 14);
define("LOG_EXPORT_PARRILLA", 15);
define("LOG_UPDATE_HOUR_PARRILLA", 16);
define("LOG_UPDATE_EVENTO", 17);

define("LOG_UPDATE_ORDER_PARRILLA", 18);
define("LOG_UPDATE_DATES_PARRILLA", 19);

define("LOG_IMPORT_EVENTOS", 20);
define("LOG_UPDATE_MOSCA2_PARRILLA", 21);
